### ISSUE TITLE
Suggestion : polygon support

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen#1468]
Hi, i got a suggestion for Denizen
adding polygon support
That can be use for polygonal selection like worldedit
 do (to max 20 selection). This way we can make script
that use this

**Comment by mcmonkey4eva** [comment]
What's the point of that? Sounds very complicated and difficult to use without a lot of helper scripts...

**Comment by Noiknez** [comment]
It is for Dregion script that i will also integrate in my script

**Comment by Morphan1** [comment]
dCuboids support multiple cuboids in one for some reason. Would it be better to just abuse that? Maybe make a list tag that turns a bunch of locations into some kind of makeshift polygon or something idk

**Comment by AnthonyAMC** [comment]
Shapes with diagonal lines would be a ridiculous mess and quite redundant abusing multiple overlapping cuboids...

**Comment by Noiknez** [comment]
I wad thinking about à " L " shape, not diagonal line when i said polygon

**Comment by mcmonkey4eva** [comment]
L shape can be accomplished with two cuboids.

**Comment by AnthonyAMC** [comment]
Yeah of course i went straight to complex polyhedra as the ultimate use case :P

**Comment by Noiknez** [comment]
Polyhedra for minecraft is not so good, instead i proposed a complex cubicuboctahedron Anthony,

It is more easy to make a L cuboid in one time instead of putting 2 cuboid, but i will do like that

**Comment by mcmonkey4eva** [comment]
Really delayed response but,

@Noiknez the request (as described in your last post) is literally what dCuboids are and have always been.
You can put multiple 'sub cuboids' within one dCuboid.

Polygons would be shapes with diagonals.

**Comment by mcmonkey4eva** [comment]
Took a few years, but we got PolygonTag now.

No polyhedra still tho
