### ISSUE TITLE
hostile-villager type entity tags

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen#1553]
I noticed that Denizen doesn't have handling of tags like the Evokers' ```SpellTicks```; Vexes' ```BoundX```, ```BoundY```, ```BoundZ```, and ```LifeTicks```; Vindicators' ```Johnny```; and Evocation fangs' ```Warmup```. I mean, I could use ```execute as_server 'minecraft:entitydata <mob UUID> {<tags>}```, but that would be filling up console and I would rather avoid those scenarios.

I also didn't see the ```spit``` and ```totem``` particle effects listed for the ```playeffect``` command.

**Comment by mcmonkey4eva** [comment]
Particles doc problem resolved

**Comment by mcmonkey4eva** [comment]
At least some of these are covered, the remainder can/will be covered if/when specifically requested by users
