### ISSUE TITLE
Schematic command doesn't copy/paste the schematic at the origin

### ISSUE THREAD

**Issue by lmorgh** [DenizenScript/Denizen#1624]
As the title suggests, the pasted schematics are offset when pasted. I tried numerous combinations when creating them. When a schematic is created and then again pasted at the same location with the same (fixed) origin, it pastes the blocks as expected, over the original blocks. But when I try to paste the schematic somewhere else with the <player.location> for origin, the pasted schem is offset by 1 block. Tags like location.center or location.simple don't help either.

**Comment by Mwthorn** [comment]
Did you make the schematics with the same dCommand? or with WorldEdit? Denizen schematics only work with denizen commands. You cannot mix WorldEdit and Denizen Schematics.
Here is the command i use to create a schematic with the WorldEdit selection:
/ex schematic create name:island_lvl4 <player.selected_region> <player.location>
/ex schematic save name:island_lvl4

**Comment by lmorgh** [comment]
I used Denizen only for this, so it has noting to do with WorldEdit. I'll check out your technique though, thanks.

**Comment by mcmonkey4eva** [comment]
That sounds like you might just be misinterpretting the placement a little? Or providing bad input numbers... worst case scenario, just manually apply an offset, EG `.add[1,1,1]`

**Comment by lmorgh** [comment]
The thing is, I've been testing this with 3x3 or 5x5 schematics, so it's easy to set the center block as the origin. To the best of my abilities I could not figure out the cause of this, the only thing I can think of is that the origin is somehow incorrectly calculated. It would be great if someone could take a few minutes and test creating/pasting a simple 3x3 schematic to see what I mean (or to prove it's an error on my end).

**Comment by mcmonkey4eva** [comment]
Tested locally on current dev build with a 5x5 with an obvious center block, stood on the center block, created a schematic, then walked into random other places and pasted it again. Seems to always behave how I would expect (ie it spawns the center block below my feet).
Considering this issue invalid.
