### ISSUE TITLE
suggestion: - engage player

### ISSUE THREAD

**Issue by BloodEko** [DenizenScript/Denizen#1735]
Here now the formal request of these 2 additions:
```
- engage player
- disengage player
```

**Comment by mcmonkey4eva** [comment]
So, the engage functionality normally for NPCs, instead done for players (such that players cannot interact with anything until disengaged) or for Players+NPCs (such that the player cannot interact with the same NPC until disengaged)?

**Comment by BloodEko** [comment]
Note for the future:
It would be actually that only the linked npc is blocked for the linked player. (Players+NPCs)

The idea behind enganging is that the same dialogue won't start twice.
Default engage archieves this, but has the disadvantage that the npc is blocked then for
all other players too, which must wait.

```
- engage player
- chat someText
- give diamond
- wait 5s
- zap step
- disengage player
```

The inner code is "locked" and guranteed to be ran only once. 
No matter how often the npc is clicked.
