### ISSUE TITLE
Request: scoreboard team options

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen#1753]
Scoreboard teams have options like name visibility, team color, etc. I didn't find any way of modifying those via the [team command](https://one.denizenscript.com/denizen/cmds/team)

**Comment by redshirt2** [comment]
I've just discovered, that if you use the denizen Team command, it creates an actual minecraft scoreboard and so, to make a team have an option, just execute as server:
- execute as_server "scoreboard teams option NoNameTags nametagVisibility never"

In this example, I've already added several NPCs and players to the team NoNameTags.  this line adds the option to hide the nametags. Pretty sure it will work for all the other options...

**Comment by MusicScore** [comment]
I believe the same happens with the `scoreboard` command. An actual objective is created, with the specified scores being assigned to specific names. However, the `scoreboard` command features near full control over the objective's features in a single command. The `team` command does not, and as far as I know only supports custom prefixes and suffixes.

**Comment by MusicScore** [comment]
Seems like the API has stuff related to this.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scoreboard/Team.html

Will add this at some point.

**Comment by mcmonkey4eva** [comment]
This was added a while back, to the `team` command.
