### ISSUE TITLE
rewrite the "on player enters/exits notable cuboid" event as ScriptEvent

### ISSUE THREAD

**Issue by waterquarks** [DenizenScript/Denizen#1799]
Seems like there are some events that haven't fully transitioned into modern Denizen, and it would be nice to have them use the script event priority functionality that ScriptEvents feature!

**Comment by realdagumboss** [comment]
Can I tag along on this suggestion to say that an "on entity enters/exits notable cuboid" event would be useful? Or is that better in it's own suggestion?

**Comment by mcmonkey4eva** [comment]
That'd be separate
