### ISSUE TITLE
Crafting Troubles Meta-Issue

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Denizen#1851]
This is a meta-issue to direct all general trouble with crafting item scripts into.

The general intended solution at the moment is to rework the item script crafting system to be driven by NMS interop with the native minecraft crafting system.
Should fix all the issues with the weird janked-on event-driven crafting system we currently use.

**Comment by mcmonkey4eva** [comment]
See my post tat bottom of #1764 for notes on how to implement.

**Comment by DerbanTC** [comment]
Is this still in progress?

It's a major bug. And it makes our server (on them I'm working with Goma) still unplayable.

**Comment by mcmonkey4eva** [comment]
Done!
