### ISSUE TITLE
Sound play event

### ISSUE THREAD

**Issue by ghost** [DenizenScript/Denizen#1854]
I have a suggestion: the event will fire when some sound plays on the server
Can be cancellable (if possible): - determine cancelled
Tags:
<context.sound> - returns Element (name) of played sound.
<context.location> - returns dLocation of played sound.
<context.volume> - returns Element of volume.
<context.pitch> - returns Element of pitch.
<context.source> - (for 1.9 or higher) - returns Element of source name (ambient/block/hostile/player/master etc.)
Example:
on sound plays (in \<area\>) (via \<source\>)
on \<sound\> plays (in \<area\>) (via \<source\>)

**Comment by modgamer** [comment]
Spigot API does not have SoundPlayEvent
This suggestion does not actual...

**Comment by mcmonkey4eva** [comment]
@Morphan1 mentioned on Discord that a fair portion of the sounds on modern minecraft setup should be sent through just these 3 main packets:

https://wiki.vg/Protocol#Named_Sound_Effect https://wiki.vg/Protocol#Sound_Effect https://wiki.vg/Protocol#Effect

Which we can intercept to make an event like this.

Though I'm worried there might be a fair amount of sounds handled by other methods (eg an entityeffect 'hurt' I believe will play the damage animation and also the sound (via just one entitystatus packet))

**Comment by mcmonkey4eva** [comment]
Closing as the original poster deleted their own account
