### ISSUE TITLE
/ex fakespawn PLAYER

### ISSUE THREAD

**Issue by DonKolia** [DenizenScript/Denizen#2348]
Command:
/ex fakespawn PLAYER <player.location> players: `<player>`

The output of `/version` on my server is:
This server is running Paper version git-Paper-379 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 276d830)

The output of `/version denizen` on my server is:
Denizen version 1.2.5-SNAPSHOT (build 6335-DEV)

A link to a paste of a script demonstrating the issue:
https://paste.denizenscript.com/View/98692

The issue is:
When i execute this command in the game or using script, the answer is the https://paste.denizenscript.com/View/98692

**Comment by mcmonkey4eva** [comment]
Yet again: support is on Discord @ https://discord.gg/Q6pZGSR
